name: Python CI pip

on:
   push:
     paths:
       - "requirements.txt"
       - "src/**"
       - "test/**"
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
                    Cache:'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt
          # python -m pip install --upgrade pip
          # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: pytest

      # - name: Use API secret (example)
      #   env:
      #     API_TOKEN: ${{ secrets.MY_SECRET }}
      #   run: |
      #     # اختبار اتصال بخدمة خارجية بدون طباعة السر
      #     response=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer $API_TOKEN" https://www.google.com/health)
      #     echo "API responded with code $response"

